# Generated by Django 3.0.6 on 2020-10-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201029_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='results',
            new_name='result',
        ),
        migrations.RenameModel(
            old_name='Scrapers',
            new_name='Scraper',
        ),
    ]
