# Generated by Django 3.0.6 on 2020-10-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201029_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='scraper_name',
            field=models.CharField(default=[], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='Description',
            field=models.TextField(default=[], null=True),
        ),
    ]
