# Generated by Django 3.0.6 on 2020-10-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201029_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='Description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='links',
            field=models.TextField(default='', null=True),
        ),
    ]
