# Generated by Django 3.1.2 on 2020-10-31 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201029_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='result',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
