# Generated by Django 3.0.6 on 2020-11-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_statementtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Description',
            field=models.TextField(default='', null=True),
        ),
    ]
