# Generated by Django 3.0.6 on 2020-11-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201101_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Facts',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='Pictures',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='home_fact',
            field=models.TextField(default='', null=True),
        ),
    ]
