# Generated by Django 3.0.6 on 2020-11-01 14:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201101_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='Facts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='result',
            name='Pictures',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='result',
            name='home_fact',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
