# Generated by Django 3.0.6 on 2020-11-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_result_rowdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='rowdata',
            new_name='rawdata',
        ),
    ]
