# Generated by Django 3.0.6 on 2020-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20201102_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='rawdata',
            field=models.TextField(default='', null=True),
        ),
    ]
