# Generated by Django 3.1.2 on 2020-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20201102_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='area',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='latlon',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='zipcode',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scraper',
            name='source',
            field=models.CharField(default='zillow', max_length=200),
        ),
    ]
